### ISSUE TITLE
Remove Wizard Examples Menu

### ISSUE THREAD

**Issue by Harikrishnadhas** [mariodavid/cuba-component-wizard#13]
After adding this add on to the project. A menu called Wizard Examples is appearing in the application. I think it is from the add-on. How to remove this menu?

**Comment by EvgeniyaVK** [comment]
> After adding this add on to the project. A menu called Wizard Examples is appearing in the application. I think it is from the add-on. How to remove this menu?

Hello! Have you solved your problem? I have the same situation.

**Comment by Harikrishnadhas** [comment]
> > After adding this add on to the project. A menu called Wizard Examples is appearing in the application. I think it is from the add-on. How to remove this menu?
> 
> Hello! Have you solved your problem? I have the same situation.

Nope! I couldn't resolve it.. Rather I got into further trouble and had to remove this add-on and move on with Tabs, as my deliverable had short deadline.

I'm planing to use this add-on when it becomes stable.

**Comment by EvgeniyaVK** [comment]
Oh, I see. Thank you for answer.

**Comment by mariodavid** [comment]
Hi,

sorry for not being responsive in this thread.

In fact it was just an error on my side exposing those examples.

I will create a new bug-fix release removing the examples. For now you can just exclude them by role permissions for all your roles. With that no-one can see them anymore.

Bye
Mario

**Comment by mariodavid** [comment]
solved in #15

**Comment by mariodavid** [comment]
released in 0.4.1: https://github.com/mariodavid/cuba-component-wizard/releases/tag/0.4.1

please check if it solves the problem.

**Comment by Harikrishnadhas** [comment]
Tested in latest version as of today. Issue is resolved.
