### ISSUE TITLE
Any chance of a port to 7.x?

### ISSUE THREAD

**Issue by typerlc** [mariodavid/cuba-component-wizard#7]
Are you planning a port to Cuba Platform 7?

I'm only new to Cuba, so I'm not really sure how to go about making the required changes myself.  I'm willing to have a go if you can provide some assistance on getting setup, and pointers on what needs changing.

**Comment by typerlc** [comment]
A few of the changes were simple, and I've made those.  However, I don't understand the event propagation mechanism.  I'm getting lots of errors like the following:

```
/Volumes/source/git/rlc/cuba-component-wizard/modules/web/src/de/diedavids/cuba/wizard/web/gui/components/WebWizard.java:84: error: cannot find symbol
        getEventRouter().addListener(WizardStepChangeListener.class, listener);
        ^
  symbol:   method getEventRouter()
  location: class WebWizard
```

**Comment by typerlc** [comment]
See initial attempt (throwing exception) PR #8

**Comment by mariodavid** [comment]
done: #10
